courses/urls.py
# from django.conf.urls import url   <--- Outdated??
from django.urls import path

from . import views

app_name = "courses"

urlpatterns = [
    path("", views.course_list, name="list"),
    path("<int:course_pk>/<int:step_pk>/", views.step_detail,
         name="step"),
    path("<int:pk>/", views.course_detail, name="detail"),
    #path('<int:pk>/', name='course_detail'),  # Käbbel?
]

learning_site/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings  # I have forgot what this does. Unused?
from django.views.static import serve  # I have forgot what this does. Unused?

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views

urlpatterns = [
    path("courses/", include("courses.urls")),  # Probably don't need the namespace="courses" inside the include
    path('admin/', admin.site.urls),
    path("", views.hello_world, name="home"),
]


urlpatterns += staticfiles_urlpatterns()

courses/models.py
from django.db import models


class Course(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=255)
    description = models.TextField()

    def __str__(self):
        return self.title

class Step(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    content = models.TextField(blank=True, default="")
    order = models.IntegerField(default=0)
    course = models.ForeignKey(Course, on_delete=models.DO_NOTHING)
    # on_delete=models.CASCADE
    # https://docs.djangoproject.com/en/1.11/ref/models/fields/#django.db.models.ForeignKey

    class Meta:
        ordering = ["order",]


    def __str__(self):
        return self.title

courses/views.py
from django.shortcuts import get_object_or_404, render

from .models import Course, Step


def course_list(request):
    courses = Course.objects.all()
    email = "questions@learningsite.com"
    return render(request, "courses/course_list.html", {"courses": courses, "email": email})


def course_detail(request, pk):
    # course = Course.objects.get(pk=pk)
    course = get_object_or_404(Course, pk=pk)
    step_count =  len(course.step_set.all())
    return render(request, "courses/course_detail.html", {"course": course, "step_count": step_count})


def step_detail(request, course_pk, step_pk):
    step = get_object_or_404(Step, course_id=course_pk, pk=step_pk)
    return render(request, "courses/step_detail.html", {"step": step})

learning_site/views.py
from django.shortcuts import render


def hello_world(request):
    return render(request, "home.html")

courses/templates/courses/course_detail.html
{% extends "layout.html" %}
{% load humanize course_extras %}

{% block title %}
    {{ course.title }}
{% endblock %}

{% block content %}
<article>
    <h2>{{ course.title }}</h2>
    <p>Created on: {{ course.created_at|date:"F j, Y" }} ({{ course.created_at|naturaltime }})</p>
    {{ course.description|markdown_to_html }}

    {% if step_count >= 2 %}
    <p>There are {{ course.step_set.count|apnumber }} step{{ course.step_set.count|pluralize }} in this course: {{ course.step_set.all|join:", " }}</p>
    {% elif step_count == 1 %}
    <p>This is the only step in this course: {{ course.step_set.all|join:"" }}</p>
    {% else %}
    <p>These is no steps in this course.</p>
    {% endif %}


    <section>
        {% for step in course.step_set.all %}
        <h3><a href="{% url 'courses:step' course_pk=step.course.pk step_pk=step.pk %}">{{ step.title }}</a></h3>
             {{ step.description }}
        {% endfor %}
    </section>
</article>
{% endblock %}

courses/templates/courses/course_list.html
{% extends "layout.html" %}
{% load static from staticfiles %}
{% load humanize %}

{% block static %}
    <link rel="stylesheet" href="{% static 'courses/css/courses.css' %}">
{% endblock %}

{% block title %}
Available Courses
{% endblock %}

{% block content %}
<div class="cards">
    {% for course in courses %}
    <div class="card">
        <header><a href="{% url 'courses:detail' pk=course.pk %}">{{ course.title }}</a></header>
        <div class="card-copy">
            {% if course.description|wordcount <= 5 %}
                {{ course.description }}
            {% else %}
                {{ course.description|truncatewords:5 }}
                <a href="{% url 'courses:detail' pk=course.pk %}">Read more</a>
            {% endif %}
            <div>Created on: {{ course.created_at|date:"F j, Y" }}</div>
        </div>
    </div>
    {% endfor %}
    <div>Have questions? Contact us! {{ email|urlize }}</div>
</div>
{% endblock %}

courses/templates/courses/course_nav.html
{% for course in courses %}
    <div><a href="{% url 'courses:detail' pk=course.pk %}">{{ course.title }}</a></div>
{% endfor %}

courses/templates/courses/step_detail.html
{% extends "layout.html" %}
{% load course_extras %}

{% block title %}
    {{ step.title }} - {{ step.course.title }}
{% endblock %}

{% block content %}
<article>
    <h2><a href="{% url 'courses:detail' pk=step.course.pk %}">{{ step.course.title }}</a></h2>
    <h3>{{ step.title }}</h3>
    {% with con=step.content %}
        {{ con|linebreaks }} Content: {{ con|wordcount }} words.
        Estimated time to complete: {{ con|wordcount|time_estimate }} minute{{ con|wordcount|time_estimate|pluralize }}.
    {% endwith %}
</article>
{% endblock %}

templates/home.html
{% extends "layout.html" %}

{% block title %}
Well hello there!
{% endblock %}

{% block content %}
<h1>Welcome!</h1>
<p>Django, very cool.</p>
{% endblock %}

templates/layout.html
{% load static from staticfiles %}
{% load course_extras %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/layout.css' %}">
    {% block static %}{% endblock %}
</head>
<body>
    <div class="site-container">
        <div>{% nav_courses_list %}</div>
        <nav>
            <a href="{% url 'home' %}">Home</a>
            <a href="{% url 'courses:list' %}">Course List</a>
        </nav>
        <p>Don't forget to check out our latest course, {% newest_course %}</a></p>
    {% block content %}{% endblock %}

    </div>
</body>
</html>